# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'last' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD_AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'B' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;

#A2T
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train A2T --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 1.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train A2T --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 1.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train A2T --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 1.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train A2T --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 1.0  --debug;

# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;

#Base MMD 
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;

# Extra MMD
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train BERTAttack --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train BERTAttack --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train BERTAttack --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train BERTAttack --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;

# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train PWWS --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train PWWS --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train PWWS --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train PWWS --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;

# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextBugger --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextBugger --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextBugger --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextBugger --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'MMD' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'True' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;

# Baseline
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'B' --save_space 'ARR_OCT_2023_FurtherTrainBaseline' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'B' --save_space 'ARR_OCT_2023_FurtherTrainBaseline' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'B' --save_space 'ARR_OCT_2023_FurtherTrainBaseline' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'B' --save_space 'ARR_OCT_2023_FurtherTrainBaseline' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;


# AT
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'AT' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;



# FLB
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;
# CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'FLB' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.0  --debug;







# Adv Train Roberta
CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextFooler --dataset 'SST2' --model 'ROBERTA' --method 'AUG' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate PWWS --dataset 'SST2' --model 'ROBERTA' --method 'AUG' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate BERTAttack --dataset 'SST2' --model 'ROBERTA' --method 'AUG' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
CUDA_VISIBLE_DEVICES=7 python ../../../high_level_at.py --attack_train TextFooler --attack_evaluate TextBugger --dataset 'SST2' --model 'ROBERTA' --method 'AUG' --save_space 'ARR_OCT_2023_Rigth_env_new_roberta_classification_head' --GPU '1.1'  --frozen 'False' --eval_method 'epoch' --epochs 3 --online_epochs 3 --batch_size 32 --data_ratio 0.1  --debug;
 